### ISSUE TITLE
white line in raster

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [jokergoo/EnrichedHeatmap#54] opened 2020-10-14 14:18 UTC
Hi jakergoo, 
I am using the EnrichedHeatmap function with the use_raster=T,raster_device = "png" 
option. What happens is that I get white raster lines (in equal distances) within the Heatmap that appear like lines without data, which is though not the case. 
![image](https://user-images.githubusercontent.com/48914703/96001655-8fe46700-0e38-11eb-97bd-0155c6fe097c.png)
Do you have an idea how I can prevent them to be created?
When I use use_raster=F, then these lines are not created, but the file is too big that Illustrator cannot handle it. 

Best, 
Clarissa

**Comment by jokergoo** [comment] 2020-10-14 15:29
I think that is a problem of the png device. Maybe you can try to set `raster_device = "jpeg"` or `raster_device = "tiff"`?

**Comment by crazyhottommy** [comment] 2020-10-14 19:07
it is also possible that you have too many rows > 10000. even with raster you get some artifacts. try to reduce the number of rows by susampling. see https://jokergoo.github.io/2020/06/30/rasterization-in-complexheatmap/ and https://gdevailly.netlify.app/post/plotting-big-matrices-in-r/

**Comment by jokergoo** [comment] 2020-10-14 19:28
I also saw these annoying white lines many times in my plots. For mine, they were vertical lines. I have no idea where they came out. Sometimes when I slightly adjusted the size of the plot, they were just gone, or if I saved the plots as PDF (with raster turned on), there were no white lines either.

Maybe it is because the default resolution of png is too low? I need to do more experiments.

**Comment by crazyhottommy** [comment] 2020-10-14 23:43
vertical lines in my case as well, I have too many columns. even after I turn on raster and save to PDF, they still show up. the computer does not have that many pixels to display the small grids if you have 100,000 columns.

**Comment by jokergoo** [comment] 2020-10-15 07:49
I think I found the reason. When saving the heatmap into a temporary png file with a relatively smaller size, because now multiple pixels from the original heatmap need to be merged into one single pixel and for some algorithms and under low-resolution setting, it is possible very few rows or columns (one or two) in the png RGB matrix are not mapped with any value, thus shown as white lines. I can confirm it by checking the RGB matrix of the temporary png file.

Ha, I think now I have some ideas to fill these missing values in the RGB matrix. Hopeful these annoying white lines will disappear.

**Comment by crazyhottommy** [comment] 2020-10-15 14:28
good catch! thanks for looking into it and make it an issue to address in the future.

**Comment by jokergoo** [comment] 2020-10-18 08:45
I created an issue in ComplexHeatmap repo, so I close this issue here.

**Closed by jokergoo** 2020-10-18 08:45 UTC

**Comment by jokergoo** [comment] 2020-10-20 13:19
Hi @ClarissaFeuersteinAkgoz , I updated the package and changed the default raster device to `CairoPNG`. As I've tested, I didn't see these white lines. Can you update the package and run on your dataset?

**Comment by ClarissaFeuersteinAkgoz** [comment] 2021-03-04 12:04
Everything working now!
Thanks!
